api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from api.views import ProjectViewSet, update_webhook, peaks, \
    sign_data, SongViewSet, fetch_user_tokens, AlbumViewSet
from comments.api.urls import router as comments_router
from player.api.urls import router as player_router
from snippets.api.urls import router as snippets_router
from sync.api.urls import router as sync_router
from sync.api.views import get_backend_creds
from users.api.urls import router as users_router

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet, 'project')
router.register(r'albums', AlbumViewSet, 'album')
router.register(r'songs', SongViewSet, 'song')

# Submodule APIs
router.registry.extend(player_router.registry)
router.registry.extend(users_router.registry)
router.registry.extend(comments_router.registry)
router.registry.extend(sync_router.registry)
router.registry.extend(snippets_router.registry)

urlpatterns = [
    path('', include(router.urls)),
    path('player/', include(player_router.urls)),
    path('sync/', include('sync.api.urls')),
    path('todo/', include('todo.api.urls')),
    path('sign/', sign_data, name='sign_data'),
    path('peaks/', peaks, name='peaks'),
    path('token/fetch/', fetch_user_tokens),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('webauth/', include('rest_framework.urls', namespace='rest_framework')),
    path('webhook/update/', update_webhook, name='update_webhook'),
    path('backend_creds/', get_backend_creds, name='backend_creds'),
]

comments/urls.py
from django.urls import path

from comments import views

app_name = 'comments'
urlpatterns = [
    path('projects/<int:proj>/comment/', views.CommentCreateView.as_view(), name='comment-create'),
    path('projects/<int:proj>/songs/<int:song>/comment/', views.CommentCreateView.as_view(),
         name='comment-create'),
    path('projects/<int:proj>/songs/<int:song>/comment/<int:pk>/delete/', views.CommentDeleteView.as_view(),
         name='comment-delete'),
    path('projects/<int:proj>/comment/<int:pk>/delete/', views.CommentDeleteView.as_view(),
         name='comment-delete'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('projects/<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('projects/<int:pk>/unsubscribe/', views.ProjectUnsubscribeView.as_view(), name='project-unsubscribe'),
    path('projects/<int:pk>/songs/create/', views.SongCreateView.as_view(), name='song-create'),
    path('projects/<int:proj>/songs/<int:song>/', views.SongDetailView.as_view(), name='song-detail'),
    path('projects/<int:proj>/songs/<int:song>/versions/', views.SongVersionView.as_view(), name='song-versions'),
    path('projects/<int:proj>/songs/<int:song>/edit/', views.SongUpdateView.as_view(), name='song-update'),
    path('projects/<int:proj>/songs/<int:song>/delete/', views.SongDeleteView.as_view(), name='song-delete'),
    path('projects/<int:proj>/songs/<int:song>/clear_peaks/', views.ClearSongPeaksView.as_view(),
         name='song-clear-peaks'),
    path('projects/<int:pk>/albums/create/', views.AlbumCreateView.as_view(), name='album-create'),
    path('projects/<int:proj>/albums/<int:album>/edit/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('projects/<int:proj>/albums/<int:album>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    path('projects/<int:proj>/songs/<int:song>/regen_url/', views.RegenSongURLView.as_view(),
         name='song-regen-url'),
]

syncprojectsweb/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from syncprojectsweb.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
                  path('', include('core.urls')),
                  path('sync/', include('sync.urls')),
                  path('todo/', include('todo.urls')),
                  path('admin/', admin.site.urls),
                  path('__debug__/', include(debug_toolbar.urls)),
                  path('api/v1/', include('api.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('users/', include('users.urls')),
                  path('snippets/', include('snippets.urls')),
              ] + static(MEDIA_URL, document_root=MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.UserDetailView.as_view(), name='user-profile'),
    path('token/', views.UserTokenView.as_view(), name='user-token'),
    path('profile/edit/', views.UserUpdateView.as_view(), name='user-update'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user-profile'),
]

comments/models.py
import timeago
from django.db import models
from django.utils import timezone

from core.models import Song, Project
from syncprojectsweb.settings import AUTH_USER_MODEL


class Tag(models.Model):
    name = models.CharField(max_length=50)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class Comment(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    assignee = models.ForeignKey(AUTH_USER_MODEL, related_name='assignee', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    requires_resolution = models.BooleanField(default=False)
    resolved = models.BooleanField(default=False)
    posted_date = models.DateTimeField(default=timezone.now)
    edited = models.BooleanField(default=False)
    song_time = models.DurationField(null=True, blank=True)
    text = models.TextField()
    song = models.ForeignKey(Song, null=True, blank=True, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, null=True, blank=True, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.SET_NULL)
    hidden = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)
    internal = models.BooleanField(default=True)

    def hide_tree(self):
        for comment in self.tree():
            comment.hidden = True
            comment.save()
            comment.hide_tree()

    def tree(self):
        return self.children.all()

    def is_root(self):
        return self.parent is None

    def when_str(self):
        return timeago.format(self.posted_date, timezone.now())

    def timecode(self):
        seconds = int(self.song_time.total_seconds())
        minutes = seconds // 60
        hours = minutes // 60
        seconds = seconds % 60
        result = ""
        if hours:
            result += f"{hours}:"
        return result + f"{minutes}:{seconds:02}"

    def __str__(self):
        if self.song:
            name = self.song.name
        else:
            name = self.project.name
        return name + ": " + self.user.username + " at " + self.posted_date.isoformat() + " says \"" + self.text[
                                                                                                       :50] + (
                   "..." if len(self.text) > 50 else "") + "\""

    @property
    def likes(self):
        return self.commentlike_set.all().count()

    def liked_by(self, user):
        try:
            return self.commentlike_set.get(user=user)
        except CommentLike.DoesNotExist:
            return None


class CommentLike(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

core/forms.py
from django import forms

from core.models import Album, Song


class AlbumForm(forms.ModelForm):
    songs = forms.ModelMultipleChoiceField(queryset=Song.objects.none(), required=False,
                                           help_text="Use ctrl to select multiple, or shift to select a range.")

    class Meta:
        model = Album
        fields = ['name', 'cover', 'released', 'release_date']

comments/api/views.py
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from rest_framework import viewsets, permissions, status
from rest_framework.decorators import action
from rest_framework.response import Response

from api.permissions import UserHasProjectMemberAccess
from api.views import HTTP_403_RESPONSE
from comments.api.serializers import CommentSerializer, TagSerializer
from comments.models import Comment, CommentLike, Tag
from core.models import Song, Project


class CommentViewSet(viewsets.ModelViewSet):
    serializer_class = CommentSerializer
    permission_classes = [permissions.IsAuthenticated, UserHasProjectMemberAccess]

    def get_queryset(self):
        project = self.request.query_params.get('project')
        song = self.request.query_params.get('song')
        for name, param in (('song', song), ('project', project)):
            if not param:
                continue
            _class = {'song': Song, 'project': Project}[name]
            try:
                obj = _class.objects.get(id=param)
            except _class.DoesNotExist:
                return Comment.objects.none()
            if not self.request.user.can_sync(obj):
                return Comment.objects.none()
            return Comment.objects.filter(**{name: obj})
        return self.request.user.comment_set.all()

    def perform_create(self, serializer):
        if self.request.data.get('song'):
            obj = Song.objects.get(id=self.request.data['song'])
        else:
            obj = Project.objects.get(id=self.request.data['project'])
        if not self.request.user.can_sync(obj) and not self.request.user.has_subscriber_access(obj):
            raise ValidationError("Access denied")
        serializer.save(user=self.request.user, internal=self.request.user.can_sync(obj))

    # noinspection PyUnusedLocal
    @action(detail=True, methods=['post'])
    def unresolve(self, request, pk=None):
        comment = Comment.objects.get(id=pk)
        if not request.user.has_member_access(comment.song):
            return HTTP_403_RESPONSE
        comment.requires_resolution = True
        comment.resolved = False
        comment.save()
        return Response({}, status=status.HTTP_204_NO_CONTENT)

    # noinspection PyUnusedLocal
    @action(detail=True, methods=['post'])
    def resolve(self, request, pk=None):
        comment = Comment.objects.get(id=pk)
        if not request.user.has_member_access(comment.song):
            return HTTP_403_RESPONSE
        comment.requires_resolution = True
        comment.resolved = True
        comment.save()
        return Response({}, status=status.HTTP_204_NO_CONTENT)

    # noinspection PyUnusedLocal
    @action(detail=True, methods=['post'])
    def like(self, request, pk=None):
        comment = Comment.objects.get(id=pk)
        if comment.song:
            obj = comment.song
        else:
            obj = comment.project
        if not request.user.has_subscriber_access(obj) and not request.user.has_member_access(obj):
            return HTTP_403_RESPONSE
        elif request.user == comment.user:
            return Response({}, status=status.HTTP_429_TOO_MANY_REQUESTS)
        like, created = CommentLike.objects.get_or_create(user=request.user, comment=comment)
        if not created:
            like.delete()
        return JsonResponse({'likes': comment.likes, 'liked': created})


class TagViewSet(viewsets.ModelViewSet):
    serializer_class = TagSerializer
    permission_classes = [permissions.IsAuthenticated, UserHasProjectMemberAccess]

    def get_queryset(self):
        project = self.request.query_params.get('project')
        try:
            project = Project.objects.get(id=project)
        except Project.DoesNotExist:
            return Tag.objects.none()
        if not self.request.user.can_sync(project):
            return Tag.objects.none()
        return Tag.objects.filter(project=project)

comments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.views import generic

from comments.models import Comment
from core.models import Project, Song


class CommentCreateView(LoginRequiredMixin, generic.CreateView):
    model = Comment
    fields = ['text', 'assignee', 'song_time']

    def form_valid(self, form):
        project = Project.objects.get(pk=self.kwargs.get('proj'))
        if 'song' in self.kwargs:
            song = Song.objects.get(pk=self.kwargs.get('song'))
            form.instance.song = song
        form.instance.project = project
        form.instance.user = self.request.user
        form.instance.save()
        return super().form_valid(form)

    def get_success_url(self):
        if self.object.song:
            return reverse('core:song-detail', args=[self.object.project.pk, self.object.song.pk])
        return reverse('core:project-detail', args=[self.object.project.pk])


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Comment

    def test_func(self):
        return self.get_object().user == self.request.user

    def get_success_url(self):
        if self.object.song:
            return reverse('core:song-detail', args=[self.object.project.pk, self.object.song.pk])
        return reverse('core:project-detail', args=[self.object.project.pk])

core/templates/core/comment.html
{% load core_extras %}
<div class="modal" tabindex="-1" id="comment-delete-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Comment</h5>
                <button type="button" class="btn-close" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="comment-delete-modal-body">
                <p class="lead">Are you sure?</p>
                <p>This comment will be deleted permanently. If you are sure, click the button below.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary">Close</button>
                <button class="btn btn-lg btn-danger" id="confirm-comment-delete" type="submit">DELETE</button>
            </div>
        </div>
    </div>
</div>
<div id="comment-div" class="col-12 col-lg-9 float-lg-start order-lg-3 order-2">
    <h2>Comments</h2>
    {% if song and song.url %}
        <button class="btn btn-primary" id="time-button">Comment at...</button>
    {% endif %}
    <form id="comment-form" method="post" action="
            {% if song %}{% url 'core:comment-create' project.id song.id %}{% else %}{% url 'core:comment-create' project.id %}{% endif %}">
        {% csrf_token %}
        <textarea name="text" id="comment-field" class="form-control"
                  placeholder="Write your comment here..."></textarea>
        {% if song %}
            <input type="hidden" name="song_time" id="song_time" value="0"/>
        {% endif %}
        <input type="submit" class="btn btn-primary" value="Post Comment">
    </form>
    <div id="comment-div-inner">
        {% for comment in comments %}
            {% if comment.is_root %}
                {% for subcomment in comment.tree %}
                    {{ subcomment }}
                {% endfor %}
            <div class="card col-md-9" id="comment-{{ comment.id }}">
                <div class="card-header">
                    <a href="{% url 'users:user-profile' comment.user.id %}">{{ comment.user.display_name }}</a>
                    &mdash; {{ comment.when_str }} ({{ comment.posted_date }})
                    {% if comment.edited %} (edited){% endif %}
                    {% if comment.requires_resolution and not comment.resolved %}
                        <span id="comment-unresolved-{{ comment.id }}" class="badge bg-warning">Unresolved</span>
                    {% endif %}
                </div>
                <div class="card-body">
                    {% if comment.song_time %}
                        <a role="button" class="timecode-link" id="time-{{ comment.song_time.total_seconds }}"
                           onclick="wavesurfer.play({{ comment.song_time.total_seconds }});"><h5
                                class="card-title">{{ comment.timecode }}</h5></a>
                    {% endif %}
                    <p class="card-text">{{ comment.text }}</p>
                    {# <a href="#" class="btn btn-sm btn-primary">Reply</a>#}
                </div>
                <div class="card-footer text-muted">
                    {% if comment.user == user %}
                        <button class="btn btn-link btn-sm text-muted">Edit</button>
                        <button id="comment-delete-btn-{{ comment.id }}"
                                class="btn btn-link btn-sm text-muted comment-delete">Delete
                        </button>
                    {% endif %}
                    <button class="btn btn-link btn-sm text-muted">Reply</button>
                    <button id="comment-like-btn-{{ comment.id }}"
                            class="btn btn-link btn-sm {% liked_by_user comment user %}text-muted comment-like"
                            {% if user == comment.user %} disabled{% endif %}><span class="fas fa-thumbs-up"></span>
                    </button>
                    <span id="comment-likes-{{ comment.id }}">{{ comment.likes }}</span>
                    <button class="btn btn-link btn-sm text-muted">Assign</button>
                    {% if comment.requires_resolution and not comment.resolved %}
                        <button id="comment-resolve-btn-{{ comment.id }}"
                                class="btn btn-link btn-sm text-muted comment-resolve">Mark as resolved
                        </button>
                    {% else %}
                        <button id="comment-unresolve-btn-{{ comment.id }}"
                                class="btn btn-link btn-sm text-muted comment-resolve">Mark as needing resolution
                        </button>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

core/templates/core/project_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load core_extras %}


{% block header %}
    <h1 class="h2">{{ project.name }} Dashboard
        {% if project.website %}
            <a href="{{ project.website }}"><span class="fas fa-external-link-alt"></span></a>
        {% endif %}
    </h1>
    {% if member %}
        <span class="badge bg-primary">Member</span>
    {% else %}
        <span class="badge bg-success">Follower</span>
    {% endif %}
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            {% include 'sync/buttons.html' %}
        </div>
        {% if member %}
            <div class="btn-group me-2">
                <a href="{% url 'core:song-create' project.id %}" class="btn btn-sm btn-outline-primary">New Song</a>
                <a href="{% url 'core:album-create' project.id %}" class="btn btn-sm btn-outline-primary">New Album</a>
                <a href="{% url 'core:project-update' project.id %}" class="btn btn-sm btn-outline-secondary">Edit
                    Project</a>
                <a href="{% url 'core:project-delete' project.id %}" class="btn btn-sm btn-outline-danger">Delete
                    Project</a>
            </div>
        {% endif %}

        {% if albums %}
            <div class="dropdown">
                <button class="btn btn-sm btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Filter albums
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    {% for album, _ in albums %}
                        <li><a class="dropdown-item"
                               href="{% url 'core:project-detail' project.id %}?album={{ album.id }}">{{ album.name }}</a>
                        </li>
                    {% endfor %}
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'core:project-detail' project.id %}?album=unsorted">Unsorted
                        only</a></li>
                    {% if filtered %}
                        <li><a class="dropdown-item" href="{% url 'core:project-detail' project.id %}">Reset filter</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
        {% if subscriber %}
            <form method="post" action="{% url 'core:project-unsubscribe' project.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-sm btn-danger">Unfollow</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

{% block sidebar %}
    {% include 'core/sidebar.html' %}
{% endblock %}


{% block content %}
    {% include 'sync/sync.html' %}
    <div class="row">
        {% if albums %}
            {% for album, songs in albums %}
                <div class="col-12 col-lg-7">
                    {% if album %}
                        <h3 class="h3">
                            {% if album.cover %}
                                <img src="{{ album.cover.url }}" width="60px"/>
                            {% endif %}
                            {{ album.name }}
                            <a style="text-decoration: none" href="{% url 'core:album-update' project.id album.id %}">
                                <span style="font-size: 8pt; color: blue;" class="fas fa-pen"></span></a>
                            <a style="text-decoration: none" href="{% url 'core:album-delete' project.id album.id %}">
                                <span style="font-size: 8pt; color: red;" class="fas fa-trash"></span></a>
                        </h3>
                        {% if album.release_date %}
                            <h6 class="text-muted">
                                {% if album.released %}{% if album.is_released %}Released{% else %}Upcoming
                                    release{% endif %}{% else %}Est.
                                    release{% endif %} {{ album.release_date }}</h6>
                        {% else %}
                            <h6 class="text-muted">{% if album.released %}Released{% else %}Unreleased{% endif %}</h6>
                        {% endif %}
                    {% else %}
                        <h3 class="h3">Unsorted</h3>
                    {% endif %}
                    <table style="margin-bottom:20px" class="table table-striped">
                        <thead>
                        <tr>
                            {% if album %}
                                <th scope="col">#</th>
                            {% endif %}
                            <th scope="col">Song</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if songs %}
                            {% for song in songs %}
                                <tr>
                                    {% if album %}
                                        <td>{% if song.album_order %}{{ song.album_order }}{% else %}{% endif %}</td>
                                    {% endif %}
                                    <td><a href="{% url 'core:song-detail' project.id song.id %}">{{ song.name }}</a>
                                    </td>
                                    <td>
                                        {% if not member and song in collab %}
                                            <span class="badge bg-info">Collaborator</span>
                                        {% endif %}
                                        {% if song.unresolved_comments.count %}
                                            <span class="fas fa-comment"></span>
                                            <span class="text-muted" title="Unresolved comments">{{ song.unresolved_comments.count }}</span>
                                        {% endif %}
                                        {% if song.is_locked %}
                                            <span title="Song is checked out" class="fas {% get_lock_icon song user %}"></span>
                                        {% endif %}
                                        {% if song.archived %}
                                            <span title="Archived" class="fas fa-box"></span>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td><p class="text-muted">No songs here.</p></td>
                                <td></td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            {% endfor %}
            <div class="col-lg-5">
                {% include 'player/project_player.html' %}
            </div>
        {% else %}
            <div class="alert alert-primary"><strong>No Songs here!</strong>{% if member %} Get started and <a
                    href="{% url 'core:song-create' project.id %}">create one</a>{% endif %}</div>
        {% endif %}
        {% include 'sync/recent_syncs.html' %}
        {% include 'comments/comments.html' %}
    </div>
{% endblock %}

{% block script %}
    {% include 'player/project_player_res.html' %}
    {% include 'sync/script.html' %}
{% endblock %}

core/templates/core/song_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block head %}
    {% if song.url %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    {% endif %}
{% endblock %}

{% block header %}
    <h1 class="h2">{{ song.name }}</h1>
    {% if song.bpm %}
        <h5 class="text-muted">{{ song.bpm }} BPM</h5>
    {% endif %}
    {% if song.key_tuning %}
        <h5 class="text-muted">{{ song.key_tuning }}</h5>
    {% endif %}
    {% if member %}
        <span class="badge bg-primary">Member</span>
    {% elif can_sync %}
        <span class="badge bg-info">Collaborator</span>
    {% else %}
        <span class="badge bg-success">Follower</span>
    {% endif %}
    {% if song.archived %}
        <span class="badge bg-danger">Archived</span>
    {% endif %}
    {% for lock in song.locks.all %}
        <span class="badge bg-danger">Checked out by
            {% if lock.user == user %}
                you
            {% else %}
                {{ lock.user }}
            {% endif %}
            since {{ lock.start_time }}</span>
    {% endfor %}
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            {% include 'sync/buttons.html' %}
        </div>
        {% if user.is_superuser %}
            <div class="btn-group me-2">
                <a href="{% url 'core:song-clear-peaks' project.id song.id %}">
                    <button type="button" class="btn btn-sm btn-outline-warning">Redraw Waveform</button>
                </a>
                <a href="{% url 'core:song-regen-url' project.id song.id %}">
                    <button type="button" class="btn btn-sm btn-outline-warning">Regen URL</button>
                </a>
            </div>
        {% endif %}
        {% if member %}
            <div class="btn-group me-2">
                <a href="{% url 'core:song-update' project.id song.id %}" class="btn btn-sm btn-outline-secondary">Edit
                    Song</a>
                <a href="{% url 'core:song-delete' project.id song.id %}" class="btn btn-sm btn-outline-danger">Delete
                    Song</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block sidebar %}
    {% include 'core/sidebar.html' %}

{% endblock %}

{% block content %}
    {% include 'sync/sync.html' %}
    {% if song.signed_url %}
        <span id="song_url_present" hidden></span>
        <div class="col-sm-1">
            <div id="MyClockDisplay" class="timecode"></div>
        </div>
        <div class="col-lg-9 col-sm-12">
            {% include 'player/player.html' %}
        </div>
        <span class="text-muted">Audio last updated: {% if song.last_audio_sync %}{{ song.last_audio_sync.date }} by
            {{ song.last_audio_sync.user }}{% else %}unknown{% endif %}</span>
        <span class="text-muted"><a href="{{ song.signed_url }}"><span title="Download" class="fas fa-download"></span></a></span>
        <a href="{% url 'core:song-versions' project.id song.id %}"><span
                class="fas fa-history" title="Previous versions"></span></a>
    {% else %}
        <div class="alert alert-dismissable alert-secondary"><strong>No audio!</strong> There is currently not an audio
            URL defined for this song. Add one to enable the player and other features.
        </div>
    {% endif %}
    {% include 'comments/comments.html' %}
    {% include 'sync/recent_syncs.html' %}
{% endblock %}

{% block script %}
    {% include 'sync/script.html' %}
    {% if song.signed_url %}
        {% include 'player/script.html' %}
    {% endif %}
{% endblock %}