api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from api.views import ProjectViewSet, update_webhook, peaks, \
    sign_data, SongViewSet, fetch_user_tokens, AlbumViewSet
from comments.api.urls import router as comments_router
from player.api.urls import router as player_router
from snippets.api.urls import router as snippets_router
from sync.api.urls import router as sync_router
from sync.api.views import get_backend_creds
from users.api.urls import router as users_router

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet, 'project')
router.register(r'albums', AlbumViewSet, 'album')
router.register(r'songs', SongViewSet, 'song')

# Submodule APIs
router.registry.extend(player_router.registry)
router.registry.extend(users_router.registry)
router.registry.extend(comments_router.registry)
router.registry.extend(sync_router.registry)
router.registry.extend(snippets_router.registry)

urlpatterns = [
    path('', include(router.urls)),
    path('player/', include(player_router.urls)),
    path('sync/', include('sync.api.urls')),
    path('todo/', include('todo.api.urls')),
    path('sign/', sign_data, name='sign_data'),
    path('peaks/', peaks, name='peaks'),
    path('token/fetch/', fetch_user_tokens),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('webauth/', include('rest_framework.urls', namespace='rest_framework')),
    path('webhook/update/', update_webhook, name='update_webhook'),
    path('backend_creds/', get_backend_creds, name='backend_creds'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('projects/<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('projects/<int:pk>/unsubscribe/', views.ProjectUnsubscribeView.as_view(), name='project-unsubscribe'),
    path('projects/<int:pk>/songs/create/', views.SongCreateView.as_view(), name='song-create'),
    path('projects/<int:proj>/songs/<int:song>/', views.SongDetailView.as_view(), name='song-detail'),
    path('projects/<int:proj>/songs/<int:song>/versions/', views.SongVersionView.as_view(), name='song-versions'),
    path('projects/<int:proj>/songs/<int:song>/edit/', views.SongUpdateView.as_view(), name='song-update'),
    path('projects/<int:proj>/songs/<int:song>/delete/', views.SongDeleteView.as_view(), name='song-delete'),
    path('projects/<int:proj>/songs/<int:song>/clear_peaks/', views.ClearSongPeaksView.as_view(),
         name='song-clear-peaks'),
    path('projects/<int:pk>/albums/create/', views.AlbumCreateView.as_view(), name='album-create'),
    path('projects/<int:proj>/albums/<int:album>/edit/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('projects/<int:proj>/albums/<int:album>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    path('projects/<int:proj>/songs/<int:song>/regen_url/', views.RegenSongURLView.as_view(),
         name='song-regen-url'),
]

sync/api/urls.py
from django.urls import path
from rest_framework import routers

from sync.api import views

router = routers.DefaultRouter()
router.register(r'syncs', views.SyncViewSet, 'sync')
router.register(r'updates', views.ClientUpdateViewSet, 'update')
router.register(r'logs', views.ClientLogViewSet, 'log')

urlpatterns = [
    path('audio_sync/', views.audio_sync, name='audio_sync'),
    path('checkouts/', views.get_checkouts, name='get_checkouts'),
]

sync/urls.py
from django.urls import path

from . import views

app_name = 'sync'
urlpatterns = [
    path('client_login/', views.send_sync_token, name='client-login'),
    path('client_login/success/', views.authorization_success, name='client-login-success'),
    path('download/', views.DownloadIndexView.as_view(), name='download-index'),
    path('logs/<int:user>/', views.UserLogIndexView.as_view(), name='log-index'),
    path('logs/<int:user>/<int:pk>', views.UserLogDetailView.as_view(), name='log-detail'),
]

syncprojectsweb/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from syncprojectsweb.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
                  path('', include('core.urls')),
                  path('sync/', include('sync.urls')),
                  path('todo/', include('todo.urls')),
                  path('admin/', admin.site.urls),
                  path('__debug__/', include(debug_toolbar.urls)),
                  path('api/v1/', include('api.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('users/', include('users.urls')),
                  path('snippets/', include('snippets.urls')),
              ] + static(MEDIA_URL, document_root=MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.UserDetailView.as_view(), name='user-profile'),
    path('token/', views.UserTokenView.as_view(), name='user-token'),
    path('profile/edit/', views.UserUpdateView.as_view(), name='user-update'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user-profile'),
]

sync/models.py
import io
import re
from zipfile import ZipFile

import timeago
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Q
from django.utils import timezone

from core.models import Project, Song
from syncprojectsweb.settings import AUTH_USER_MODEL


class Sync(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    sync_time = models.DateTimeField(default=timezone.now)
    songs = models.ManyToManyField(Song)

    def last_sync_str(self):
        return timeago.format(self.sync_time, timezone.now())

    def __str__(self):
        return f"{self.user} sync at {self.sync_time} on {self.project}"


class SupportedClientTarget(models.Model):
    target = models.CharField(max_length=100, unique=True)
    icon = models.CharField(max_length=50, null=True, blank=True)
    friendly_name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.target

    def name(self) -> str:
        return self.friendly_name or self.target

    def render_icon(self) -> str:
        return f'<span class="fab fa-{self.icon}"></span>' if self.icon else ''

    def latest_release(self):
        return self.clientupdate_set.filter(visible=True).last()


class ClientUpdate(models.Model):
    version = models.CharField(max_length=20)
    updater = models.FileField(upload_to='updates/updater/', null=True, blank=True)
    package = models.FileField(upload_to='updates/')
    target = models.ForeignKey(SupportedClientTarget, null=True, blank=True, on_delete=models.PROTECT)
    visible = models.BooleanField(default=True)

    def __str__(self):
        return f"v{self.version}-{self.target}"

    def latest_updater(self) -> str:
        if self.updater:
            return self.updater.url
        try:
            return ClientUpdate.objects.filter(~Q(updater=''), target=self.target).order_by('-id')[0].updater.url
        except IndexError:
            return None


class ChangelogEntry(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    text = models.TextField()
    date_created = models.DateTimeField(default=timezone.now)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    sync = models.ForeignKey(Sync, null=True, on_delete=models.SET_NULL, related_name='changelog')

    def __str__(self):
        return f"{self.date_created.isoformat()} by {self.user} on {self.song}"


class ClientLog(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    log_compressed = models.BinaryField()

    def __str__(self):
        return f"{self.user} - {self.date}"

    def uncompressed(self):
        z = io.BytesIO(self.log_compressed)
        with ZipFile(z) as z:
            with z.open(z.namelist()[0]) as log:
                return log.read().decode(errors="ignore")


class AudioSync(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.song} audio synced at {self.date} by {self.user}"


class ClientFeatureChangelog(models.Model):
    version = models.CharField(max_length=20, unique=True)
    date = models.DateField(default=timezone.now, null=True, blank=True)
    changes = models.TextField()

    def __str__(self):
        return str(self.version)

    def format_changes(self):
        return re.sub(r'((^|\n)##?) ', r'\1###', self.changes)

sync/api/views.py
from rest_framework import viewsets, permissions, status
from rest_framework.decorators import action, api_view, permission_classes
from rest_framework.response import Response

from api.permissions import UserHasProjectAccess, CreateOrReadOnly, IsAdminOrWriteOnly
from api.serializers import LockSerializer
from api.views import HTTP_403_RESPONSE, HTTP_404_RESPONSE
from core.models import Song, Project, Lock
from sync.api.serializers import ClientUpdateSerializer, SyncSerializer, ChangelogEntrySerializer, ClientLogSerializer
from sync.models import SupportedClientTarget, ClientUpdate, Sync, ChangelogEntry, ClientLog, AudioSync
from syncprojectsweb.settings import BACKEND_ACCESS_ID, BACKEND_SECRET_KEY


class ClientUpdateViewSet(viewsets.ModelViewSet):
    serializer_class = ClientUpdateSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        target = self.request.query_params.get('target')
        if target:
            try:
                target = SupportedClientTarget.objects.get(target=target)
            except SupportedClientTarget.DoesNotExist:
                return ClientUpdate.objects.none()
            return ClientUpdate.objects.filter(target=target, visible=True)
        else:
            return ClientUpdate.objects.filter(target__isnull=True, visible=True)


class SyncViewSet(viewsets.ModelViewSet):
    serializer_class = SyncSerializer
    permission_classes = [permissions.IsAuthenticated, UserHasProjectAccess, CreateOrReadOnly]

    def get_queryset(self):
        song = self.request.query_params.get('song')
        revision = int(self.request.query_params.get('since_revision', 0))
        if not song:
            return Sync.objects.none()
        return Sync.objects.filter(songs=song)[revision:]

    def retrieve(self, request, pk=None):
        sync = super().retrieve(request, pk)
        sync.data['changelogs'] = ChangelogEntrySerializer(self.get_object().changelog, many=True, read_only=True).data
        return Response(sync.data)

    # noinspection PyUnusedLocal
    @action(detail=True, methods=['put'])
    def changelog(self, request, pk=None):
        # TODO: validate
        song = Song.objects.get(id=pk)
        if not self.request.user.can_sync(song):
            return HTTP_403_RESPONSE
        sync = song.sync_set.all().last()
        result = ChangelogEntry.objects.create(user=self.request.user,
                                               sync=sync,
                                               song=song,
                                               text=request.data['text'])
        return Response({'created': result.id})

    # noinspection PyUnusedLocal
    @action(detail=True, methods=['get'])
    def get_changelogs(self, request, pk=None):
        song = Song.objects.get(id=pk)
        if not self.request.user.can_sync(song):
            return HTTP_403_RESPONSE
        try:
            revision = int(request.query_params.get('since'))
        except (TypeError, ValueError):
            revision = None
        if revision is None:
            return HTTP_404_RESPONSE
        lookback = song.revision - revision
        result = ChangelogEntry.objects.filter(song=song).order_by('-id')[:lookback]
        return Response(ChangelogEntrySerializer(result, many=True).data)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class ClientLogViewSet(viewsets.ModelViewSet):
    serializer_class = ClientLogSerializer
    permission_classes = [permissions.IsAuthenticated, IsAdminOrWriteOnly]
    queryset = ClientLog.objects.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user, log_compressed=self.request.FILES.get('log_compressed').read())


@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def get_backend_creds(request):
    return Response({'access_id': BACKEND_ACCESS_ID, 'secret_key': BACKEND_SECRET_KEY})


@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def audio_sync(request):
    try:
        project = Project.objects.get(name=request.data['project'])
        song = Song.objects.get(name__iexact=request.data['song'], project=project)
    except (Song.DoesNotExist, Project.DoesNotExist):
        return HTTP_404_RESPONSE
    if not request.user.can_sync(song):
        return HTTP_403_RESPONSE
    AudioSync.objects.create(user=request.user, song=song)
    song.peaks = ""
    song.save()
    return Response({}, status=status.HTTP_204_NO_CONTENT)


@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def get_checkouts(request):
    return Response({'checkouts': LockSerializer(Lock.objects.filter(user=request.user), many=True).data})

sync/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.views import generic

from api.utils import get_tokens_for_user
from sync.models import SupportedClientTarget, ClientLog, ClientFeatureChangelog
from sync.utils import get_signed_data


@login_required
def send_sync_token(request):
    return render(request, 'sync/login.html',
                  {'auth_data': get_signed_data(get_tokens_for_user(request.user))})


@login_required
def authorization_success(request):
    return render(request, 'sync/authz_complete.html')


class DownloadIndexView(LoginRequiredMixin, generic.ListView):
    model = SupportedClientTarget
    template_name = 'sync/download.html'
    context_object_name = 'supported_targets'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_changes'] = ClientFeatureChangelog.objects.all().order_by('-id')
        context['show_dl'] = not self.request.GET.get('show_dl') == '0'
        return context


class UserLogBaseView(LoginRequiredMixin, UserPassesTestMixin):
    model = ClientLog

    def test_func(self):
        return self.request.user.is_superuser

    def get_queryset(self):
        return ClientLog.objects.filter(user_id=self.kwargs['user'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['log_user'] = get_user_model().objects.get(id=self.kwargs['user'])
        return context


class UserLogIndexView(UserLogBaseView, generic.ListView):
    pass


class UserLogDetailView(UserLogBaseView, generic.DetailView):
    pass

sync/templates/sync/authz_complete.html
{% extends 'registration/base.html' %}
{% load static %}
{% block title %}Authorization Success{% endblock %}
{% block content %}
    <main class="form-signin">
        <img class="mb-4" src="{% static 'img/syncprojects.png' %}" alt="Syncprojects"/>
        <h1>Success!</h1>
        <p>You have successfully authorized the client application. You may either close this tab, or return <a
                href="/">home</a>.</p>
    </main>
{% endblock %}

sync/templates/sync/buttons.html
{% if member or can_sync or not project %}
    <button class="btn btn-sm btn-success" id="sync_button" hidden>Download Sync Client <span
            class="fas fa-download"></span></button>
    {% if song %}
        <button class="btn btn-sm btn-success" id="daw_button" disabled hidden>Sync & Open <span
                class="fas fa-arrow-up-right-from-square"></span></button>
        <button class="btn btn-sm btn-danger" id="undo_button" hidden>Undo Checkout <span class="fas fa-bomb"></span>
        </button>
    {% endif %}
{% endif %}

sync/templates/sync/client_changes.html
{% load markdownify %}
{% if client_changes %}
    <div id="sync-changes-body">
    {% if show_dl %}
        <hr>
    {% endif %}
        <h3>Client Changelog</h3>
        {% for change in client_changes %}
            <div class="row">
                <div class="card" style="margin-top: 10px;">
                    <div class="card-body">
                        <h4 class="card-title">
                            {{ change.version }}{% if change.date %} - {{ change.date }}{% endif %}</h4>
                        {{ change.format_changes|markdownify }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endif %}

sync/templates/sync/clientlog_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block sidebar_container %}{% endblock %}

{% block header %}
    <h1 class="h2">View Client Logs for {{ log_user }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
{% endblock %}

{% block content %}
    <h3>{{ clientlog }}</h3>
    <pre>
        {{ clientlog.uncompressed }}
    </pre>
{% endblock %}

sync/templates/sync/clientlog_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block sidebar_container %}{% endblock %}

{% block header %}
    <h1 class="h2">View Client Logs for {{ log_user }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
{% endblock %}

{% block content %}
    {% for log in clientlog_list %}
        <div class="card">
            <div class="card-body">
                <a href="{% url 'sync:log-detail' log_user.id log.id %}">{{ log }}</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

sync/templates/sync/download.html
{% extends 'core/base.html' %}
{% load static %}

{% block sidebar_container %}{% endblock %}

{% block header %}
    {% if show_dl %}
        <h1 class="h2">Download Syncprojects Client</h1>
    {% else %}
        <h1 class="h2">What's New in Syncprojects Client</h1>
    {% endif %}
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
{% endblock %}

{% block content %}
    {% if show_dl %}
        <div class="row">
            {% if supported_targets %}
                {% for target in supported_targets %}
                    {% if target.latest_release %}
                    <div class="col-md-2">
                        <div class="card" style="margin-top: 10px;">
                            <div class="card-body">
                                <h5 class="card-title">{{ target.name }} {{ target.render_icon|safe }}</h5>
                                <a href="{{ target.latest_release.package.url }}"
                                   class="card-link">Download {{ target.latest_release.version }}</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <div class="alert alert-danger" role="alert">
                No downloads available at this time!
            </div>
        {% endif %}
    </div>
    {% endif %}
    <div class="row">
        {% include 'sync/client_changes.html' %}
    </div>
{% endblock %}

sync/templates/sync/login.html
{% extends 'registration/base.html' %}
{% load static %}
{% block title %}Syncprojects Client Authorization{% endblock %}
{% block content %}
    <main class="form-signin">
        <img class="mb-4" src="{% static 'img/syncprojects.png' %}" alt="Syncprojects"/>
        <p>Logging you in...</p>
    </main>
    <input type="hidden" id="auth_token" value="{{ auth_data }}">
    <input type="hidden" id="redirect_url" value="{% url 'sync:client-login-success' %}">
    <script src="{% static 'sync/api.js' %}"></script>
    <script src="{% static 'sync/auth.js' %}"></script>
{% endblock %}

sync/templates/sync/recent_syncs.html
{% if member %}
    <div class="col-lg-3 col-12 float-lg-end align-self-center">
        <div class="card">
            <h4 class="text-center">Recent Syncs</h4>
            {% if syncs %}
                {% if song %}
                    {% for sync, changelog in syncs %}
                        <div class="card">
                            <div class="card-header">
                            <span class="text-primary"><a
                                    href="{% url 'users:user-profile' sync.user.id %}">{{ sync.user }}</a></span> {{ sync.last_sync_str }}
                                <span class="text-muted">({{ sync.sync_time }})</span>
                            </div>
                            <div class="card-body">
                                {% if changelog.text %}
                                    <span>
                                    {{ changelog.text }}
                                {% else %}
                                    <span class="text-muted">
                                    No changes were provided.
                                {% endif %}
                                </span>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    {% for sync in syncs %}
                        <div class="card">
                            <div class="card-header">
                            <span class="text-primary"><a
                                    href="{% url 'users:user-profile' sync.user.id %}">{{ sync.user }}</a></span> {{ sync.last_sync_str }}
                                <span class="text-muted">({{ sync.sync_time }})</span>
                            </div>
                            <div class="card-body">
                                {% if sync.changelog.all|length %}
                                    {% for changelog in sync.changelog.all %}
                                        <p>
                                            <a href="{% url 'core:song-detail' project.id changelog.song.id %}">{{ changelog.song.name }}:</a>
                                        </p>
                                        {% if changelog.text %}
                                            <p>
                                                {{ changelog.text|truncatechars:40 }}
                                                {% if changelog.text.len > 40 %}
                                                    ...
                                                {% endif %}
                                            </p>
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    {% for song in sync.songs.all %}
                                        <p>
                                            <a href="{% url 'core:song-detail' project.id song.id %}">{{ song.name }}</a>
                                        </p>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            {% else %}
                <span class="text-muted text-center">No syncs yet. Get to work!</span>
            {% endif %}
        </div>
    </div>
{% endif %}

sync/templates/sync/script.html
{% load static %}
{% if member or can_sync or not project %}
    <script src="{% static 'sync/api.js' %}"></script>
    <script src="{% static 'sync/sync_ui.js' %}"></script>
{% endif %}

sync/templates/sync/sync.html
{% if member or can_sync or not project %}
    {% csrf_token %}
    <div class="modal" tabindex="-1" id="sync_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Sync Results</h5>
                    <button type="button" class="btn-close close-sync-modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="sync-modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary close-sync-modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" id="undo_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Undo Checkout</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="undo-modal-body">
                    <h3>Are you sure?</h3>
                    <p>All your local changes will be lost, and your files will be replaced by what's on the server.</p>
                    <p>This process is irreversible! Make sure you haven't created anything great since you last checked
                        in.</p>
                </div>
                <div class="modal-footer">
                    <span id="undo_countdown"></span>
                    <button type="button" class="btn btn-danger" id="final_undo_button" data-bs-dismiss="modal"
                            disabled>Confirm Undo <span class="fas fa-bomb"></span></button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="progress" id="sync_progress" hidden>
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 100%"
             aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <div id="safari" class="alert alert-danger" hidden>
        Safari does not properly follow web browser standards set by the World Wide Web Consortium (W3C) and therefore
        does not work with the syncprojects client. Please use another browser that properly follows the standards, such
        as Google Chrome or Mozilla Firefox.
    </div>
{% endif %}