api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from api.views import ProjectViewSet, update_webhook, peaks, \
    sign_data, SongViewSet, fetch_user_tokens, AlbumViewSet
from comments.api.urls import router as comments_router
from player.api.urls import router as player_router
from snippets.api.urls import router as snippets_router
from sync.api.urls import router as sync_router
from sync.api.views import get_backend_creds
from users.api.urls import router as users_router

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet, 'project')
router.register(r'albums', AlbumViewSet, 'album')
router.register(r'songs', SongViewSet, 'song')

# Submodule APIs
router.registry.extend(player_router.registry)
router.registry.extend(users_router.registry)
router.registry.extend(comments_router.registry)
router.registry.extend(sync_router.registry)
router.registry.extend(snippets_router.registry)

urlpatterns = [
    path('', include(router.urls)),
    path('player/', include(player_router.urls)),
    path('sync/', include('sync.api.urls')),
    path('todo/', include('todo.api.urls')),
    path('sign/', sign_data, name='sign_data'),
    path('peaks/', peaks, name='peaks'),
    path('token/fetch/', fetch_user_tokens),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('webauth/', include('rest_framework.urls', namespace='rest_framework')),
    path('webhook/update/', update_webhook, name='update_webhook'),
    path('backend_creds/', get_backend_creds, name='backend_creds'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('projects/<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('projects/<int:pk>/unsubscribe/', views.ProjectUnsubscribeView.as_view(), name='project-unsubscribe'),
    path('projects/<int:pk>/songs/create/', views.SongCreateView.as_view(), name='song-create'),
    path('projects/<int:proj>/songs/<int:song>/', views.SongDetailView.as_view(), name='song-detail'),
    path('projects/<int:proj>/songs/<int:song>/versions/', views.SongVersionView.as_view(), name='song-versions'),
    path('projects/<int:proj>/songs/<int:song>/edit/', views.SongUpdateView.as_view(), name='song-update'),
    path('projects/<int:proj>/songs/<int:song>/delete/', views.SongDeleteView.as_view(), name='song-delete'),
    path('projects/<int:proj>/songs/<int:song>/clear_peaks/', views.ClearSongPeaksView.as_view(),
         name='song-clear-peaks'),
    path('projects/<int:pk>/albums/create/', views.AlbumCreateView.as_view(), name='album-create'),
    path('projects/<int:proj>/albums/<int:album>/edit/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('projects/<int:proj>/albums/<int:album>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    path('projects/<int:proj>/songs/<int:song>/regen_url/', views.RegenSongURLView.as_view(),
         name='song-regen-url'),
]

syncprojectsweb/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from syncprojectsweb.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
                  path('', include('core.urls')),
                  path('sync/', include('sync.urls')),
                  path('todo/', include('todo.urls')),
                  path('admin/', admin.site.urls),
                  path('__debug__/', include(debug_toolbar.urls)),
                  path('api/v1/', include('api.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('users/', include('users.urls')),
                  path('snippets/', include('snippets.urls')),
              ] + static(MEDIA_URL, document_root=MEDIA_ROOT)

todo/api/urls.py
from django.urls import path
from rest_framework import routers

from todo.api import views

router = routers.DefaultRouter()

urlpatterns = [
    path('check/', views.handle_check, name='todo_check'),
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('list/<int:project>/', views.TodoListView.as_view(), name='list-todo'),
    path('new/<int:project>/', views.TodoCreateView.as_view(), name='create-todo'),
    path('edit/<int:pk>/', views.TodoUpdateView.as_view(), name='update-todo'),
    path('delete/<int:pk>/', views.TodoDeleteView.as_view(), name='delete-todo'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.UserDetailView.as_view(), name='user-profile'),
    path('token/', views.UserTokenView.as_view(), name='user-token'),
    path('profile/edit/', views.UserUpdateView.as_view(), name='user-update'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user-profile'),
]

todo/models.py
from django.db import models
from django.utils import timezone

from core.models import Project, Song
from syncprojectsweb.settings import AUTH_USER_MODEL


class Todo(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, null=True, blank=True, on_delete=models.CASCADE, help_text="Optional")
    assignee = models.ForeignKey(AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE, help_text="Optional")
    created = models.DateTimeField(default=timezone.now)
    due = models.DateTimeField(null=True, blank=True, help_text="Optional; YYYY-MM-DD")
    done = models.BooleanField(default=False)
    text = models.TextField()

    def __str__(self):
        return self.project.name + " " + self.text

todo/api/views.py
from django.http import JsonResponse
from rest_framework import permissions
from rest_framework.decorators import permission_classes, api_view, authentication_classes

from api.utils import CsrfExemptSessionAuthentication
from api.views import HTTP_404_RESPONSE, HTTP_403_RESPONSE
from todo.models import Todo


@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
@authentication_classes([CsrfExemptSessionAuthentication])
def handle_check(request):
    try:
        todo = Todo.objects.get(id=request.data['id'])
    except Todo.DoesNotExist:
        return HTTP_404_RESPONSE
    if not request.user.can_sync(todo.project):
        return HTTP_403_RESPONSE
    todo.done = not todo.done
    todo.save()
    return JsonResponse({'checked': todo.done})

todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import F
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from core.models import Project
from core.permissions import UserCanSyncMixin
from todo.models import Todo

TODO_FIELDS = ['song', 'assignee', 'due', 'text']


class ProjectContextMixin(UserPassesTestMixin):
    def test_func(self):
        project = get_object_or_404(Project, id=self.kwargs['project'])
        return self.request.user.can_sync(project)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        project = get_object_or_404(Project, id=self.kwargs['project'])
        context['project'] = project
        context['member'] = self.request.user.has_member_access(project)
        return context


class TodoListView(LoginRequiredMixin, ProjectContextMixin, generic.ListView):
    model = Todo

    def get_queryset(self):
        project = get_object_or_404(Project, id=self.kwargs['project'])
        return project.todo_set.order_by('done', F('due').asc(nulls_last=True))


class TodoCreateView(LoginRequiredMixin, ProjectContextMixin, generic.CreateView):
    model = Todo
    fields = TODO_FIELDS

    def get_success_url(self):
        return reverse('todo:list-todo', args=[self.object.project.pk])

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['song'].queryset = Project.objects.get(
            id=self.kwargs['project']).song_set.all()
        if form.instance:
            form.fields['song'].initial = form.instance.song
        return form

    def form_valid(self, form):
        project = Project.objects.get(pk=self.kwargs['project'])
        form.instance.project = project
        form.instance.save()
        return super().form_valid(form)


class TodoDeleteView(LoginRequiredMixin, UserCanSyncMixin, generic.DeleteView):
    model = Todo

    def get_success_url(self):
        return reverse('todo:list-todo', args=[self.object.project.pk])


class TodoUpdateView(LoginRequiredMixin, UserCanSyncMixin, generic.UpdateView):
    model = Todo
    fields = TODO_FIELDS

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['song'].queryset = form.instance.project.song_set.all()
        if form.instance:
            form.fields['song'].initial = form.instance.song
        return form

    def get_success_url(self):
        return reverse('todo:list-todo', args=[self.object.project.pk])

todo/templates/todo/todo_confirm_delete.html
{% extends 'core/base.html' %}
{% load bootstrap5 %}


{% block header %}
    <h1 class="h2">Delete TODO</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
{% endblock %}
{% block content %}
    {% bootstrap_messages %}
    <div class="alert alert-danger">
        <p class="lead">Are you sure?</p>
    </div>
    <li class="list-group-item">
        <input id="todo-{{ todo.id }}" class="form-check-input me-1 todo-checkbox" type="checkbox" value=""
               aria-label="..." {% if todo.done %}checked{% endif %} disabled>
        <span id="todo-text-{{ todo.id }}"{% if todo.done %}
              class="text-muted text-decoration-line-through"{% endif %}>{% if todo.song %}
            <a href="{% url 'core:song-detail' todo.project.id todo.song.id %}">{{ todo.song.name }}</a>
            &mdash; {% endif %}{{ todo.text }}{% if todo.assignee %} &rarr; (
            <a href="{% url 'users:user-profile' todo.assignee.id %}">{{ todo.assignee.display_name }}</a>
            ){% endif %}</span>
    </li>
    <br>
    <form class="form" method="post">
        {% csrf_token %}
        <button class="btn btn-lg btn-danger" type="submit">DELETE</button>
    </form>
{% endblock %}

todo/templates/todo/todo_form.html
{% extends 'core/base.html' %}
{% load bootstrap5 %}

{% block header %}
    <h1 class="h2">{% if todo %}Edit{% else %}Create New{% endif %} TODO for Project {{ project.name }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
{% endblock %}

{% block sidebar %}
    {% include 'core/sidebar.html' %}
{% endblock %}

{% block content %}
    {% bootstrap_messages %}
    <form class="form" method="post">
        {% bootstrap_form form %}
        {% csrf_token %}
        <br>
        {% if todo %}
            <button class="btn btn-lg btn-primary" type="submit">Update</button>
        {% else %}
            <button class="btn btn-lg btn-primary" type="submit">Create</button>
        {% endif %}
        {% if todo %}
            <a href="{% url 'todo:list-todo' todo.project.id %}" class="btn btn-secondary">Cancel</a>
        {% else %}
            <a href="{% url 'todo:list-todo' project.id %}" class="btn btn-secondary">Cancel</a>
        {% endif %}
    </form>
{% endblock %}

todo/templates/todo/todo_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block header %}
    <h1 class="h2">{{ project.name }}</h1>
    {% if member %}
        <span class="badge bg-primary">Member</span>
    {% elif can_sync %}
        <span class="badge bg-info">Collaborator</span>
    {% else %}
        <span class="badge bg-success">Follower</span>
    {% endif %}
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url 'todo:create-todo' project.id %}" class="btn btn-sm btn-primary">New TODO <span
                    class="fas fa-plus"></span></a>
        </div>
    </div>
{% endblock %}

{% block sidebar %}
    {% include 'core/sidebar.html' %}
{% endblock %}

{% block content %}
    <h3>TODOs</h3>

    {% if todo_list %}
        <ul class="list-group">
            {% for todo in todo_list %}
                <li class="list-group-item">
                    <input id="todo-{{ todo.id }}" class="form-check-input me-1 todo-checkbox" type="checkbox" value=""
                           aria-label="..." {% if todo.done %}checked{% endif %}>
                    <span id="todo-text-{{ todo.id }}"{% if todo.done %}
                          class="text-muted text-decoration-line-through"{% endif %}>{% if todo.song %}
                        <a href="{% url 'core:song-detail' project.id todo.song.id %}">{{ todo.song.name }}</a>
                        &mdash; {% endif %}{{ todo.text }}{% if todo.assignee %} &rarr;
                        (<a href="{% url 'users:user-profile' todo.assignee.id %}">{{ todo.assignee.display_name }}</a>)
                    {% endif %}</span>
                    {% if todo.due %}
                        <span class="text-muted">by {{ todo.due.date }}</span>
                    {% endif %}
                    <a style="text-decoration: none" href="{% url 'todo:update-todo' todo.id %}">
                        <span style="font-size: 6pt; color: #c7c7c7;" class="fas fa-pencil-alt"></span></a>
                    <a style="text-decoration: none" href="{% url 'todo:delete-todo' todo.id %}">
                        <span style="font-size: 6pt; color: #c7c7c7;" class="fas fa-trash"></span></a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="alert alert-primary" role="alert">
            No todos here! <a href="{% url 'todo:create-todo' project.id %}">Create one</a>.
        </div>
    {% endif %}
{% endblock %}

{% block script %}
    <script src="{% static 'todo/todo.js' %}"></script>
{% endblock %}