api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from api.views import ProjectViewSet, update_webhook, peaks, \
    sign_data, SongViewSet, fetch_user_tokens, AlbumViewSet
from comments.api.urls import router as comments_router
from player.api.urls import router as player_router
from snippets.api.urls import router as snippets_router
from sync.api.urls import router as sync_router
from sync.api.views import get_backend_creds
from users.api.urls import router as users_router

router = routers.DefaultRouter()
router.register(r'projects', ProjectViewSet, 'project')
router.register(r'albums', AlbumViewSet, 'album')
router.register(r'songs', SongViewSet, 'song')

# Submodule APIs
router.registry.extend(player_router.registry)
router.registry.extend(users_router.registry)
router.registry.extend(comments_router.registry)
router.registry.extend(sync_router.registry)
router.registry.extend(snippets_router.registry)

urlpatterns = [
    path('', include(router.urls)),
    path('player/', include(player_router.urls)),
    path('sync/', include('sync.api.urls')),
    path('todo/', include('todo.api.urls')),
    path('sign/', sign_data, name='sign_data'),
    path('peaks/', peaks, name='peaks'),
    path('token/fetch/', fetch_user_tokens),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('webauth/', include('rest_framework.urls', namespace='rest_framework')),
    path('webhook/update/', update_webhook, name='update_webhook'),
    path('backend_creds/', get_backend_creds, name='backend_creds'),
]

sync/urls.py
from django.urls import path

from . import views

app_name = 'sync'
urlpatterns = [
    path('client_login/', views.send_sync_token, name='client-login'),
    path('client_login/success/', views.authorization_success, name='client-login-success'),
    path('download/', views.DownloadIndexView.as_view(), name='download-index'),
    path('logs/<int:user>/', views.UserLogIndexView.as_view(), name='log-index'),
    path('logs/<int:user>/<int:pk>', views.UserLogDetailView.as_view(), name='log-detail'),
]

syncprojectsweb/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from syncprojectsweb.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
                  path('', include('core.urls')),
                  path('sync/', include('sync.urls')),
                  path('todo/', include('todo.urls')),
                  path('admin/', admin.site.urls),
                  path('__debug__/', include(debug_toolbar.urls)),
                  path('api/v1/', include('api.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('users/', include('users.urls')),
                  path('snippets/', include('snippets.urls')),
              ] + static(MEDIA_URL, document_root=MEDIA_ROOT)

users/api/urls.py
from django.urls import include, path
from rest_framework import routers

from users.api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet, 'user')

urlpatterns = [
    path('', include(router.urls))
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('profile/', views.UserDetailView.as_view(), name='user-profile'),
    path('token/', views.UserTokenView.as_view(), name='user-token'),
    path('profile/edit/', views.UserUpdateView.as_view(), name='user-update'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='user-profile'),
]

users/models.py
import re
from django.contrib.auth.models import AbstractUser
from django.db import models
from rest_framework.authtoken.models import Token

from core.models import Project, Song, Album, FeatureChangelog
from sync.models import Sync


class User(AbstractUser):
    email = models.EmailField(max_length=254, unique=True)
    projects = models.ManyToManyField(Project, blank=True)
    subscribed_projects = models.ManyToManyField(Project, blank=True, related_name="subscribed_users")
    collab_songs = models.ManyToManyField(Song, blank=True, related_name="collaborating_users")
    profile_picture = models.ImageField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    instruments = models.TextField(null=True, blank=True)
    genres_musical_taste = models.TextField(null=True, blank=True, verbose_name="Genres and Musical Taste")
    open_to_collaboration = models.BooleanField(default=False)
    private = models.BooleanField(default=True,
                                  help_text="Profiles of private accounts will have their details hidden.")
    latest_feature_seen = models.ForeignKey(FeatureChangelog, null=True, blank=True, on_delete=models.SET_NULL)
    links = models.TextField(null=True, blank=True, help_text="Insert URLs (separated by space, comma, or newline) for "
                                                              "your music, website, or social media, "
                                                              "and we'll automatically display them.")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        db_table = 'auth_user'

    # TODO: social_links

    def display_name(self):
        return self.first_name or self.email

    @staticmethod
    def check_object_access(obj, projects) -> bool:
        if isinstance(obj, Project):
            try:
                projects.get(id=obj.id)
                return True
            except Project.DoesNotExist:
                return False
        elif isinstance(obj, Song) or isinstance(obj, Album):
            try:
                projects.get(id=obj.project.id)
                return True
            except Project.DoesNotExist:
                return False
        elif isinstance(obj, Sync):
            return obj.project in projects.all()
        elif hasattr(obj, 'project'):
            return User.check_object_access(obj.project, projects)
        elif hasattr(obj, 'song'):
            return User.check_object_access(obj.song, projects)
        elif hasattr(obj, 'object'):
            return User.check_object_access(obj.object, projects)
        else:
            raise NotImplementedError()

    def has_member_access(self, obj):
        return self.check_object_access(obj, self.projects)

    def has_subscriber_access(self, obj):
        return self.check_object_access(obj, self.subscribed_projects)

    def can_sync(self, obj):
        return self.has_member_access(obj) or obj in self.collab_songs.all()

    def __str__(self):
        return self.display_name()

    def get_profile(self):
        return (
            ('Bio', self.bio),
            ('Instruments', self.instruments),
            ('Genres/Musical Taste', self.genres_musical_taste),
        )

    def render_links(self):
        return [link for link in re.split(r'[, \n]', self.links) if re.match(r'https?:\/\/', link)]

    def token(self):
        try:
            return Token.objects.get(user=self)
        except Token.DoesNotExist:
            pass

users/api/views.py
from rest_framework import viewsets, permissions
from rest_framework.response import Response

from api.permissions import AdminOrSelfOnly
from users.api.serializers import UserSerializer
from users.models import User


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated, AdminOrSelfOnly]

    def get_queryset(self):
        if self.request.user.is_superuser:
            return User.objects.all().order_by('-date_joined')
        return User.objects.filter(pk=self.request.user.pk)

    def retrieve(self, request, pk=None):
        if pk == "self" or pk == request.user.pk:
            user = request.user
        elif request.user.is_superuser:
            user = User.objects.get(pk=pk)
        else:
            return super().retrieve(request, pk)
        return Response(UserSerializer(user, context={'request': request}).data)

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic, View
from rest_framework.authtoken.models import Token


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()

    def get_context_object_name(self, obj):
        return 'profile_user'

    def get_object(self, queryset=None):
        return get_user_model().objects.get(id=self.kwargs['pk']) if 'pk' in self.kwargs else self.request.user


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    template_name_suffix = '_update_form'
    model = get_user_model()
    fields = ['email', 'profile_picture', 'bio',
              'instruments', 'genres_musical_taste', 'links', 'open_to_collaboration',
              'private']

    def get_object(self, queryset=None):
        return self.request.user

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('users:user-profile')


class UserTokenView(LoginRequiredMixin, View):
    def post(self, *args, **kwargs):
        token, created = Token.objects.get_or_create(user=self.request.user)
        if not created:
            token.delete()
            Token.objects.create(user=self.request.user)
        return redirect('users:user-profile')

users/templates/users/user_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}
    {% if profile_user == user %}
        <title>User Profile</title>
    {% else %}
        <title>{{ profile_user }}'s Profile</title>
    {% endif %}
{% endblock %}

{% block head %}
{% endblock %}

{% block header %}
    <h1 class="h2">
        {% if profile_user.is_private %}
            {{ profile_user.get_short_name }}
        {% else %}
            {{ profile_user.get_full_name }}
        {% endif %}
    </h1>
    <h6>({{ profile_user.email }})</h6>
    <div class="btn-toolbar mb-2 mb-md-0">
        {% if user == profile_user %}
            <div class="btn-group me-2">
                <a href="{% url 'users:user-update' %}" class="btn btn-sm btn-primary">Edit Profile</a>
            </div>
            <div class="btn-group me-2">
                <a href="{% url 'sync:client-login' %}" class="btn btn-sm btn-outline-secondary">Authorize Client</a>
                <button id="sync-disable" class="btn btn-sm btn-outline-secondary">Disable sync for browser</button>
            </div>
            <div class="btn-group me-2">
                <form method="post" action="{% url 'users:user-token' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-outline-secondary">(Re)generate Token</button>
                </form>
            </div>
            <div class="btn-group me-2">
                {% if user.token %}
                    <button onclick="alert('{{ user.token }}');" class="btn btn-sm btn-outline-secondary">Show
                        Token
                    </button>
                {% endif %}
            </div>
        {% endif %}
        {% if user.is_superuser %}
            <div class="btn-group me-2">
                <a href="{% url 'sync:log-index' profile_user.id %}" class="btn btn-sm btn-outline-warning">View
                    Logs</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block sidebar %}
    {% if profile_user.profile_picture %}
        <div class="nav flex-column">
            <img src="{{ profile_user.profile_picture.url }}" width="75%"
                 style="padding-left: 10px; object-fit: cover; object-position: center">
        </div>
    {% endif %}

    {% include 'core/sidebar.html' %}

{% endblock %}

{% block content %}
    {% if not profile_user.is_private %}
        {% for title, text in profile_user.get_profile %}
            <div class="col-lg-3 col-sm-12 float-start" style="margin-right: 5px;">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">{{ title }}</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ text }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if profile_user.links %}
            <div class="col-lg-3 col-sm-12 float-start" style="margin-right: 5px;">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Links</h5>
                    </div>
                    <div class="card-body">
                        {% for link in profile_user.render_links %}
                            <p class="card-text"><a href="{{ link }}">{{ link }}</a></p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    {% else %}
        <span class="text-muted">This user prefers to keep an air of mystery about them.</span>
    {% endif %}
{% endblock %}

users/templates/users/user_update_form.html
{% extends 'core/base.html' %}
{% load bootstrap5 %}

{% block header %}
    <h1 class="h2">Edit user profile for {{ user }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
    {% bootstrap_messages %}
    <form enctype="multipart/form-data" method="post" action="">
        {% bootstrap_form form %}
        {% csrf_token %}
        <br>
        <button class="btn btn-lg btn-primary" type="submit">Save Changes</button>
        <a href="{% url 'users:user-profile' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}